# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msgB.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'msgB.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmsgB.proto\"\xc9\x01\n\rClientMessage\x12$\n\x08msg_type\x18\x01 \x02(\x0e\x32\x12.ClientMessageType\x12\n\n\x02id\x18\x02 \x02(\t\x12\x10\n\x08wKeyDown\x18\x03 \x02(\x08\x12\x10\n\x08\x61KeyDown\x18\x04 \x02(\x08\x12\x10\n\x08sKeyDown\x18\x05 \x02(\x08\x12\x10\n\x08\x64KeyDown\x18\x06 \x02(\x08\x12\x0e\n\x06wKeyUp\x18\x07 \x02(\x08\x12\x0e\n\x06\x61KeyUp\x18\x08 \x02(\x08\x12\x0e\n\x06sKeyUp\x18\t \x02(\x08\x12\x0e\n\x06\x64KeyUp\x18\n \x02(\x08\"A\n\rServerMessage\x12$\n\x08msg_type\x18\x01 \x02(\x0e\x32\x12.ServerMessageType\x12\n\n\x02id\x18\x02 \x02(\t\"?\n\nShipStruct\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\r\n\x05\x61ngle\x18\x04 \x02(\x02\"#\n\x0bTrashStruct\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"J\n\x0cPlanetStruct\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\x16\n\x0erecycler_index\x18\x04 \x02(\x05\"\xd8\x01\n\x14UniverseStateMessage\x12\x1a\n\x05ships\x18\x01 \x03(\x0b\x32\x0b.ShipStruct\x12\"\n\x0ctrash_pieces\x18\x02 \x03(\x0b\x32\x0c.TrashStruct\x12\x1e\n\x07planets\x18\x03 \x03(\x0b\x32\r.PlanetStruct\x12\x15\n\runiverse_size\x18\x04 \x02(\x05\x12\x11\n\tgame_over\x18\x05 \x02(\x08\x12\x0c\n\x04\x62g_r\x18\x06 \x02(\x05\x12\x0c\n\x04\x62g_g\x18\x07 \x02(\x05\x12\x0c\n\x04\x62g_b\x18\x08 \x02(\x05\x12\x0c\n\x04\x62g_a\x18\t \x02(\x05\"q\n\x10\x44\x61shboardMessage\x12\x16\n\x0erecycled_trash\x18\x01 \x03(\x05\x12\x12\n\nship_cargo\x18\x02 \x03(\x05\x12\x15\n\rroaming_trash\x18\x03 \x02(\x05\x12\x1a\n\x12max_trash_capacity\x18\x04 \x02(\x05*:\n\x11\x43lientMessageType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x12\x08\n\x04MOVE\x10\x02*&\n\x11ServerMessageType\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGETYPE']._serialized_start=797
  _globals['_CLIENTMESSAGETYPE']._serialized_end=855
  _globals['_SERVERMESSAGETYPE']._serialized_start=857
  _globals['_SERVERMESSAGETYPE']._serialized_end=895
  _globals['_CLIENTMESSAGE']._serialized_start=15
  _globals['_CLIENTMESSAGE']._serialized_end=216
  _globals['_SERVERMESSAGE']._serialized_start=218
  _globals['_SERVERMESSAGE']._serialized_end=283
  _globals['_SHIPSTRUCT']._serialized_start=285
  _globals['_SHIPSTRUCT']._serialized_end=348
  _globals['_TRASHSTRUCT']._serialized_start=350
  _globals['_TRASHSTRUCT']._serialized_end=385
  _globals['_PLANETSTRUCT']._serialized_start=387
  _globals['_PLANETSTRUCT']._serialized_end=461
  _globals['_UNIVERSESTATEMESSAGE']._serialized_start=464
  _globals['_UNIVERSESTATEMESSAGE']._serialized_end=680
  _globals['_DASHBOARDMESSAGE']._serialized_start=682
  _globals['_DASHBOARDMESSAGE']._serialized_end=795
# @@protoc_insertion_point(module_scope)
