/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msgB.pb-c.h"
void   client_message__init
                     (ClientMessage         *message)
{
  static const ClientMessage init_value = CLIENT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_message__get_packed_size
                     (const ClientMessage *message)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_message__pack
                     (const ClientMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_message__pack_to_buffer
                     (const ClientMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMessage *)
     protobuf_c_message_unpack (&client_message__descriptor,
                                allocator, len, data);
}
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_message__init
                     (ServerMessage         *message)
{
  static const ServerMessage init_value = SERVER_MESSAGE__INIT;
  *message = init_value;
}
size_t server_message__get_packed_size
                     (const ServerMessage *message)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_message__pack
                     (const ServerMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_message__pack_to_buffer
                     (const ServerMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerMessage *
       server_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerMessage *)
     protobuf_c_message_unpack (&server_message__descriptor,
                                allocator, len, data);
}
void   server_message__free_unpacked
                     (ServerMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ship_struct__init
                     (ShipStruct         *message)
{
  static const ShipStruct init_value = SHIP_STRUCT__INIT;
  *message = init_value;
}
size_t ship_struct__get_packed_size
                     (const ShipStruct *message)
{
  assert(message->base.descriptor == &ship_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ship_struct__pack
                     (const ShipStruct *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ship_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ship_struct__pack_to_buffer
                     (const ShipStruct *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ship_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShipStruct *
       ship_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShipStruct *)
     protobuf_c_message_unpack (&ship_struct__descriptor,
                                allocator, len, data);
}
void   ship_struct__free_unpacked
                     (ShipStruct *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ship_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trash_struct__init
                     (TrashStruct         *message)
{
  static const TrashStruct init_value = TRASH_STRUCT__INIT;
  *message = init_value;
}
size_t trash_struct__get_packed_size
                     (const TrashStruct *message)
{
  assert(message->base.descriptor == &trash_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trash_struct__pack
                     (const TrashStruct *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trash_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trash_struct__pack_to_buffer
                     (const TrashStruct *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trash_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrashStruct *
       trash_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrashStruct *)
     protobuf_c_message_unpack (&trash_struct__descriptor,
                                allocator, len, data);
}
void   trash_struct__free_unpacked
                     (TrashStruct *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trash_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planet_struct__init
                     (PlanetStruct         *message)
{
  static const PlanetStruct init_value = PLANET_STRUCT__INIT;
  *message = init_value;
}
size_t planet_struct__get_packed_size
                     (const PlanetStruct *message)
{
  assert(message->base.descriptor == &planet_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planet_struct__pack
                     (const PlanetStruct *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planet_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planet_struct__pack_to_buffer
                     (const PlanetStruct *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planet_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlanetStruct *
       planet_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlanetStruct *)
     protobuf_c_message_unpack (&planet_struct__descriptor,
                                allocator, len, data);
}
void   planet_struct__free_unpacked
                     (PlanetStruct *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planet_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_state_message__init
                     (UniverseStateMessage         *message)
{
  static const UniverseStateMessage init_value = UNIVERSE_STATE_MESSAGE__INIT;
  *message = init_value;
}
size_t universe_state_message__get_packed_size
                     (const UniverseStateMessage *message)
{
  assert(message->base.descriptor == &universe_state_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_state_message__pack
                     (const UniverseStateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_state_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_state_message__pack_to_buffer
                     (const UniverseStateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_state_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseStateMessage *
       universe_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseStateMessage *)
     protobuf_c_message_unpack (&universe_state_message__descriptor,
                                allocator, len, data);
}
void   universe_state_message__free_unpacked
                     (UniverseStateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_state_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dashboard_message__init
                     (DashboardMessage         *message)
{
  static const DashboardMessage init_value = DASHBOARD_MESSAGE__INIT;
  *message = init_value;
}
size_t dashboard_message__get_packed_size
                     (const DashboardMessage *message)
{
  assert(message->base.descriptor == &dashboard_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dashboard_message__pack
                     (const DashboardMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dashboard_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dashboard_message__pack_to_buffer
                     (const DashboardMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dashboard_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DashboardMessage *
       dashboard_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DashboardMessage *)
     protobuf_c_message_unpack (&dashboard_message__descriptor,
                                allocator, len, data);
}
void   dashboard_message__free_unpacked
                     (DashboardMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dashboard_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client_message__field_descriptors[10] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, msg_type),
    &client_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wKeyDown",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, wkeydown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aKeyDown",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, akeydown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sKeyDown",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, skeydown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dKeyDown",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, dkeydown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wKeyUp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, wkeyup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aKeyUp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, akeyup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sKeyUp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, skeyup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dKeyUp",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, dkeyup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_message__field_indices_by_name[] = {
  3,   /* field[3] = aKeyDown */
  7,   /* field[7] = aKeyUp */
  5,   /* field[5] = dKeyDown */
  9,   /* field[9] = dKeyUp */
  1,   /* field[1] = id */
  0,   /* field[0] = msg_type */
  4,   /* field[4] = sKeyDown */
  8,   /* field[8] = sKeyUp */
  2,   /* field[2] = wKeyDown */
  6,   /* field[6] = wKeyUp */
};
static const ProtobufCIntRange client_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor client_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientMessage",
  "ClientMessage",
  "ClientMessage",
  "",
  sizeof(ClientMessage),
  10,
  client_message__field_descriptors,
  client_message__field_indices_by_name,
  1,  client_message__number_ranges,
  (ProtobufCMessageInit) client_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_message__field_descriptors[2] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerMessage, msg_type),
    &server_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_message__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = msg_type */
};
static const ProtobufCIntRange server_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerMessage",
  "ServerMessage",
  "ServerMessage",
  "",
  sizeof(ServerMessage),
  2,
  server_message__field_descriptors,
  server_message__field_indices_by_name,
  1,  server_message__number_ranges,
  (ProtobufCMessageInit) server_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ship_struct__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShipStruct, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipStruct, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipStruct, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angle",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipStruct, angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ShipStruct, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ship_struct__field_indices_by_name[] = {
  3,   /* field[3] = angle */
  4,   /* field[4] = enable */
  0,   /* field[0] = name */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange ship_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ship_struct__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShipStruct",
  "ShipStruct",
  "ShipStruct",
  "",
  sizeof(ShipStruct),
  5,
  ship_struct__field_descriptors,
  ship_struct__field_indices_by_name,
  1,  ship_struct__number_ranges,
  (ProtobufCMessageInit) ship_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trash_struct__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TrashStruct, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TrashStruct, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trash_struct__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange trash_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trash_struct__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrashStruct",
  "TrashStruct",
  "TrashStruct",
  "",
  sizeof(TrashStruct),
  2,
  trash_struct__field_descriptors,
  trash_struct__field_indices_by_name,
  1,  trash_struct__number_ranges,
  (ProtobufCMessageInit) trash_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planet_struct__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PlanetStruct, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PlanetStruct, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PlanetStruct, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recycler_index",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlanetStruct, recycler_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planet_struct__field_indices_by_name[] = {
  0,   /* field[0] = name */
  3,   /* field[3] = recycler_index */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange planet_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor planet_struct__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlanetStruct",
  "PlanetStruct",
  "PlanetStruct",
  "",
  sizeof(PlanetStruct),
  4,
  planet_struct__field_descriptors,
  planet_struct__field_indices_by_name,
  1,  planet_struct__number_ranges,
  (ProtobufCMessageInit) planet_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_state_message__field_descriptors[9] =
{
  {
    "ships",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseStateMessage, n_ships),
    offsetof(UniverseStateMessage, ships),
    &ship_struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash_pieces",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseStateMessage, n_trash_pieces),
    offsetof(UniverseStateMessage, trash_pieces),
    &trash_struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planets",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseStateMessage, n_planets),
    offsetof(UniverseStateMessage, planets),
    &planet_struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "universe_size",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, universe_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_over",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, game_over),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bg_r",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, bg_r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bg_g",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, bg_g),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bg_b",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, bg_b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bg_a",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStateMessage, bg_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_state_message__field_indices_by_name[] = {
  8,   /* field[8] = bg_a */
  7,   /* field[7] = bg_b */
  6,   /* field[6] = bg_g */
  5,   /* field[5] = bg_r */
  4,   /* field[4] = game_over */
  2,   /* field[2] = planets */
  0,   /* field[0] = ships */
  1,   /* field[1] = trash_pieces */
  3,   /* field[3] = universe_size */
};
static const ProtobufCIntRange universe_state_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor universe_state_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseStateMessage",
  "UniverseStateMessage",
  "UniverseStateMessage",
  "",
  sizeof(UniverseStateMessage),
  9,
  universe_state_message__field_descriptors,
  universe_state_message__field_indices_by_name,
  1,  universe_state_message__number_ranges,
  (ProtobufCMessageInit) universe_state_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dashboard_message__field_descriptors[4] =
{
  {
    "recycled_trash",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DashboardMessage, n_recycled_trash),
    offsetof(DashboardMessage, recycled_trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ship_cargo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DashboardMessage, n_ship_cargo),
    offsetof(DashboardMessage, ship_cargo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roaming_trash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DashboardMessage, roaming_trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_trash_capacity",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DashboardMessage, max_trash_capacity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dashboard_message__field_indices_by_name[] = {
  3,   /* field[3] = max_trash_capacity */
  0,   /* field[0] = recycled_trash */
  2,   /* field[2] = roaming_trash */
  1,   /* field[1] = ship_cargo */
};
static const ProtobufCIntRange dashboard_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dashboard_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DashboardMessage",
  "DashboardMessage",
  "DashboardMessage",
  "",
  sizeof(DashboardMessage),
  4,
  dashboard_message__field_descriptors,
  dashboard_message__field_indices_by_name,
  1,  dashboard_message__number_ranges,
  (ProtobufCMessageInit) dashboard_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue client_message_type__enum_values_by_number[3] =
{
  { "CONNECT", "CLIENT_MESSAGE_TYPE__CONNECT", 0 },
  { "DISCONNECT", "CLIENT_MESSAGE_TYPE__DISCONNECT", 1 },
  { "MOVE", "CLIENT_MESSAGE_TYPE__MOVE", 2 },
};
static const ProtobufCIntRange client_message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex client_message_type__enum_values_by_name[3] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 1 },
  { "MOVE", 2 },
};
const ProtobufCEnumDescriptor client_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientMessageType",
  "ClientMessageType",
  "ClientMessageType",
  "",
  3,
  client_message_type__enum_values_by_number,
  3,
  client_message_type__enum_values_by_name,
  1,
  client_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue server_message_type__enum_values_by_number[2] =
{
  { "OK", "SERVER_MESSAGE_TYPE__OK", 0 },
  { "ERROR", "SERVER_MESSAGE_TYPE__ERROR", 1 },
};
static const ProtobufCIntRange server_message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex server_message_type__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor server_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ServerMessageType",
  "ServerMessageType",
  "ServerMessageType",
  "",
  2,
  server_message_type__enum_values_by_number,
  2,
  server_message_type__enum_values_by_name,
  1,
  server_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
