/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

#ifndef PROTOBUF_C_msgB_2eproto__INCLUDED
#define PROTOBUF_C_msgB_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct ClientMessage ClientMessage;
typedef struct ServerMessage ServerMessage;
typedef struct ShipStruct ShipStruct;
typedef struct TrashStruct TrashStruct;
typedef struct PlanetStruct PlanetStruct;
typedef struct UniverseStateMessage UniverseStateMessage;
typedef struct DashboardMessage DashboardMessage;


/* --- enums --- */

/*
 *============Client/server connections and moves===================
 */
typedef enum _ClientMessageType {
  CLIENT_MESSAGE_TYPE__CONNECT = 0,
  CLIENT_MESSAGE_TYPE__DISCONNECT = 1,
  CLIENT_MESSAGE_TYPE__MOVE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_MESSAGE_TYPE)
} ClientMessageType;
typedef enum _ServerMessageType {
  SERVER_MESSAGE_TYPE__OK = 0,
  SERVER_MESSAGE_TYPE__ERROR = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SERVER_MESSAGE_TYPE)
} ServerMessageType;

/* --- messages --- */

struct  ClientMessage
{
  ProtobufCMessage base;
  ClientMessageType msg_type;
  /*
   *we need this for when the client disconnects
   */
  char *id;
  /*
   *bools for each key, 2 bools per key (down and up)
   */
  protobuf_c_boolean wkeydown;
  protobuf_c_boolean akeydown;
  protobuf_c_boolean skeydown;
  protobuf_c_boolean dkeydown;
  protobuf_c_boolean wkeyup;
  protobuf_c_boolean akeyup;
  protobuf_c_boolean skeyup;
  protobuf_c_boolean dkeyup;
};
#define CLIENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_message__descriptor) \
, CLIENT_MESSAGE_TYPE__CONNECT, NULL, 0, 0, 0, 0, 0, 0, 0, 0 }


/*
 *servidor responde com OK/ERROR e o id da nave de volta
 */
struct  ServerMessage
{
  ProtobufCMessage base;
  ServerMessageType msg_type;
  char *id;
};
#define SERVER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_message__descriptor) \
, SERVER_MESSAGE_TYPE__OK, NULL }


/*
 *clients need to know the position, angle and name of each ship
 */
struct  ShipStruct
{
  ProtobufCMessage base;
  char *name;
  float x;
  float y;
  float angle;
  protobuf_c_boolean enable;
};
#define SHIP_STRUCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ship_struct__descriptor) \
, NULL, 0, 0, 0, 0 }


/*
 *clients need to know the position of each trash piece
 */
struct  TrashStruct
{
  ProtobufCMessage base;
  float x;
  float y;
};
#define TRASH_STRUCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trash_struct__descriptor) \
, 0, 0 }


/*
 *clients need to know the position, name and the index of the recycler planet
 */
struct  PlanetStruct
{
  ProtobufCMessage base;
  char *name;
  float x;
  float y;
  /*
   *index of recycler planet
   */
  int32_t recycler_index;
};
#define PLANET_STRUCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planet_struct__descriptor) \
, NULL, 0, 0, 0 }


struct  UniverseStateMessage
{
  ProtobufCMessage base;
  /*
   *repeated because they're all vectors
   */
  size_t n_ships;
  ShipStruct **ships;
  size_t n_trash_pieces;
  TrashStruct **trash_pieces;
  size_t n_planets;
  PlanetStruct **planets;
  /*
   *universe size
   */
  int32_t universe_size;
  /*
   *need to know gameover state
   */
  protobuf_c_boolean game_over;
  /*
   *bg color
   */
  int32_t bg_r;
  int32_t bg_g;
  int32_t bg_b;
  int32_t bg_a;
};
#define UNIVERSE_STATE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_state_message__descriptor) \
, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0 }


/*
 *server message to dashboard 
 */
struct  DashboardMessage
{
  ProtobufCMessage base;
  /*
   *vector with recycled trash counts per planet
   */
  size_t n_recycled_trash;
  int32_t *recycled_trash;
  /*
   *vector with cargo counts per ship
   */
  size_t n_ship_cargo;
  int32_t *ship_cargo;
  /*
   *number of roaming trash pieces in universe
   */
  int32_t roaming_trash;
  /*
   *max trash capacity of universe
   */
  int32_t max_trash_capacity;
};
#define DASHBOARD_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dashboard_message__descriptor) \
, 0,NULL, 0,NULL, 0, 0 }


/* ClientMessage methods */
void   client_message__init
                     (ClientMessage         *message);
size_t client_message__get_packed_size
                     (const ClientMessage   *message);
size_t client_message__pack
                     (const ClientMessage   *message,
                      uint8_t             *out);
size_t client_message__pack_to_buffer
                     (const ClientMessage   *message,
                      ProtobufCBuffer     *buffer);
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator);
/* ServerMessage methods */
void   server_message__init
                     (ServerMessage         *message);
size_t server_message__get_packed_size
                     (const ServerMessage   *message);
size_t server_message__pack
                     (const ServerMessage   *message,
                      uint8_t             *out);
size_t server_message__pack_to_buffer
                     (const ServerMessage   *message,
                      ProtobufCBuffer     *buffer);
ServerMessage *
       server_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_message__free_unpacked
                     (ServerMessage *message,
                      ProtobufCAllocator *allocator);
/* ShipStruct methods */
void   ship_struct__init
                     (ShipStruct         *message);
size_t ship_struct__get_packed_size
                     (const ShipStruct   *message);
size_t ship_struct__pack
                     (const ShipStruct   *message,
                      uint8_t             *out);
size_t ship_struct__pack_to_buffer
                     (const ShipStruct   *message,
                      ProtobufCBuffer     *buffer);
ShipStruct *
       ship_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ship_struct__free_unpacked
                     (ShipStruct *message,
                      ProtobufCAllocator *allocator);
/* TrashStruct methods */
void   trash_struct__init
                     (TrashStruct         *message);
size_t trash_struct__get_packed_size
                     (const TrashStruct   *message);
size_t trash_struct__pack
                     (const TrashStruct   *message,
                      uint8_t             *out);
size_t trash_struct__pack_to_buffer
                     (const TrashStruct   *message,
                      ProtobufCBuffer     *buffer);
TrashStruct *
       trash_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trash_struct__free_unpacked
                     (TrashStruct *message,
                      ProtobufCAllocator *allocator);
/* PlanetStruct methods */
void   planet_struct__init
                     (PlanetStruct         *message);
size_t planet_struct__get_packed_size
                     (const PlanetStruct   *message);
size_t planet_struct__pack
                     (const PlanetStruct   *message,
                      uint8_t             *out);
size_t planet_struct__pack_to_buffer
                     (const PlanetStruct   *message,
                      ProtobufCBuffer     *buffer);
PlanetStruct *
       planet_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planet_struct__free_unpacked
                     (PlanetStruct *message,
                      ProtobufCAllocator *allocator);
/* UniverseStateMessage methods */
void   universe_state_message__init
                     (UniverseStateMessage         *message);
size_t universe_state_message__get_packed_size
                     (const UniverseStateMessage   *message);
size_t universe_state_message__pack
                     (const UniverseStateMessage   *message,
                      uint8_t             *out);
size_t universe_state_message__pack_to_buffer
                     (const UniverseStateMessage   *message,
                      ProtobufCBuffer     *buffer);
UniverseStateMessage *
       universe_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_state_message__free_unpacked
                     (UniverseStateMessage *message,
                      ProtobufCAllocator *allocator);
/* DashboardMessage methods */
void   dashboard_message__init
                     (DashboardMessage         *message);
size_t dashboard_message__get_packed_size
                     (const DashboardMessage   *message);
size_t dashboard_message__pack
                     (const DashboardMessage   *message,
                      uint8_t             *out);
size_t dashboard_message__pack_to_buffer
                     (const DashboardMessage   *message,
                      ProtobufCBuffer     *buffer);
DashboardMessage *
       dashboard_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dashboard_message__free_unpacked
                     (DashboardMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ClientMessage_Closure)
                 (const ClientMessage *message,
                  void *closure_data);
typedef void (*ServerMessage_Closure)
                 (const ServerMessage *message,
                  void *closure_data);
typedef void (*ShipStruct_Closure)
                 (const ShipStruct *message,
                  void *closure_data);
typedef void (*TrashStruct_Closure)
                 (const TrashStruct *message,
                  void *closure_data);
typedef void (*PlanetStruct_Closure)
                 (const PlanetStruct *message,
                  void *closure_data);
typedef void (*UniverseStateMessage_Closure)
                 (const UniverseStateMessage *message,
                  void *closure_data);
typedef void (*DashboardMessage_Closure)
                 (const DashboardMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    client_message_type__descriptor;
extern const ProtobufCEnumDescriptor    server_message_type__descriptor;
extern const ProtobufCMessageDescriptor client_message__descriptor;
extern const ProtobufCMessageDescriptor server_message__descriptor;
extern const ProtobufCMessageDescriptor ship_struct__descriptor;
extern const ProtobufCMessageDescriptor trash_struct__descriptor;
extern const ProtobufCMessageDescriptor planet_struct__descriptor;
extern const ProtobufCMessageDescriptor universe_state_message__descriptor;
extern const ProtobufCMessageDescriptor dashboard_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msgB_2eproto__INCLUDED */
