/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msgB.pb-c.h"
void   client__init
                     (Client         *message)
{
  static const Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_data__init
                     (UniverseData         *message)
{
  static const UniverseData init_value = UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t universe_data__get_packed_size
                     (const UniverseData *message)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_data__pack
                     (const UniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_data__pack_to_buffer
                     (const UniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseData *)
     protobuf_c_message_unpack (&universe_data__descriptor,
                                allocator, len, data);
}
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message)
{
  static const SimplifiedUniverseData init_value = SIMPLIFIED_UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData *message)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimplifiedUniverseData *)
     protobuf_c_message_unpack (&simplified_universe_data__descriptor,
                                allocator, len, data);
}
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_connect_message__init
                     (ClientConnectMessage         *message)
{
  static const ClientConnectMessage init_value = CLIENT_CONNECT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_connect_message__get_packed_size
                     (const ClientConnectMessage *message)
{
  assert(message->base.descriptor == &client_connect_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_connect_message__pack
                     (const ClientConnectMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_connect_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_connect_message__pack_to_buffer
                     (const ClientConnectMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_connect_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConnectMessage *
       client_connect_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConnectMessage *)
     protobuf_c_message_unpack (&client_connect_message__descriptor,
                                allocator, len, data);
}
void   client_connect_message__free_unpacked
                     (ClientConnectMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_connect_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_connect_message__init
                     (ServerConnectMessage         *message)
{
  static const ServerConnectMessage init_value = SERVER_CONNECT_MESSAGE__INIT;
  *message = init_value;
}
size_t server_connect_message__get_packed_size
                     (const ServerConnectMessage *message)
{
  assert(message->base.descriptor == &server_connect_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_connect_message__pack
                     (const ServerConnectMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_connect_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_connect_message__pack_to_buffer
                     (const ServerConnectMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_connect_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerConnectMessage *
       server_connect_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerConnectMessage *)
     protobuf_c_message_unpack (&server_connect_message__descriptor,
                                allocator, len, data);
}
void   server_connect_message__free_unpacked
                     (ServerConnectMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_connect_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Client, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instruction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Client, instruction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  1,   /* field[1] = instruction */
  0,   /* field[0] = key */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  2,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_data__field_descriptors[4] =
{
  {
    "Planets",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, planets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ships",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, ships),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Trash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myPlanet",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(UniverseData, myplanet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_data__field_indices_by_name[] = {
  0,   /* field[0] = Planets */
  1,   /* field[1] = Ships */
  2,   /* field[2] = Trash */
  3,   /* field[3] = myPlanet */
};
static const ProtobufCIntRange universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseData",
  "UniverseData",
  "UniverseData",
  "",
  sizeof(UniverseData),
  4,
  universe_data__field_descriptors,
  universe_data__field_indices_by_name,
  1,  universe_data__number_ranges,
  (ProtobufCMessageInit) universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simplified_universe_data__field_descriptors[4] =
{
  {
    "planetTrashCount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, planettrashcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trashPerShip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, trashpership),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freeTrash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, freetrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTrash",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, maxtrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simplified_universe_data__field_indices_by_name[] = {
  2,   /* field[2] = freeTrash */
  3,   /* field[3] = maxTrash */
  0,   /* field[0] = planetTrashCount */
  1,   /* field[1] = trashPerShip */
};
static const ProtobufCIntRange simplified_universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor simplified_universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "",
  sizeof(SimplifiedUniverseData),
  4,
  simplified_universe_data__field_descriptors,
  simplified_universe_data__field_indices_by_name,
  1,  simplified_universe_data__number_ranges,
  (ProtobufCMessageInit) simplified_universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_connect_message__field_descriptors[1] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientConnectMessage, msg_type),
    &client_connect_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_connect_message__field_indices_by_name[] = {
  0,   /* field[0] = msg_type */
};
static const ProtobufCIntRange client_connect_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_connect_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientConnectMessage",
  "ClientConnectMessage",
  "ClientConnectMessage",
  "",
  sizeof(ClientConnectMessage),
  1,
  client_connect_message__field_descriptors,
  client_connect_message__field_indices_by_name,
  1,  client_connect_message__number_ranges,
  (ProtobufCMessageInit) client_connect_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_connect_message__field_descriptors[2] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerConnectMessage, msg_type),
    &server_connect_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerConnectMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_connect_message__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = msg_type */
};
static const ProtobufCIntRange server_connect_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_connect_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerConnectMessage",
  "ServerConnectMessage",
  "ServerConnectMessage",
  "",
  sizeof(ServerConnectMessage),
  2,
  server_connect_message__field_descriptors,
  server_connect_message__field_indices_by_name,
  1,  server_connect_message__number_ranges,
  (ProtobufCMessageInit) server_connect_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue client_connect_message_type__enum_values_by_number[2] =
{
  { "CONNECT", "CLIENT_CONNECT_MESSAGE_TYPE__CONNECT", 0 },
  { "DISCONNECT", "CLIENT_CONNECT_MESSAGE_TYPE__DISCONNECT", 1 },
};
static const ProtobufCIntRange client_connect_message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex client_connect_message_type__enum_values_by_name[2] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 1 },
};
const ProtobufCEnumDescriptor client_connect_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientConnectMessageType",
  "ClientConnectMessageType",
  "ClientConnectMessageType",
  "",
  2,
  client_connect_message_type__enum_values_by_number,
  2,
  client_connect_message_type__enum_values_by_name,
  1,
  client_connect_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue server_connect_message_type__enum_values_by_number[2] =
{
  { "OK", "SERVER_CONNECT_MESSAGE_TYPE__OK", 0 },
  { "ERROR", "SERVER_CONNECT_MESSAGE_TYPE__ERROR", 1 },
};
static const ProtobufCIntRange server_connect_message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex server_connect_message_type__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor server_connect_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ServerConnectMessageType",
  "ServerConnectMessageType",
  "ServerConnectMessageType",
  "",
  2,
  server_connect_message_type__enum_values_by_number,
  2,
  server_connect_message_type__enum_values_by_name,
  1,
  server_connect_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
