/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

#ifndef PROTOBUF_C_msgB_2eproto__INCLUDED
#define PROTOBUF_C_msgB_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Client Client;
typedef struct UniverseData UniverseData;
typedef struct SimplifiedUniverseData SimplifiedUniverseData;
typedef struct ClientMessage ClientMessage;
typedef struct ServerMessage ServerMessage;


/* --- enums --- */

/*
 *============Client/server connections and moves===================
 */
typedef enum _ClientMessageType {
  CLIENT_MESSAGE_TYPE__CONNECT = 0,
  CLIENT_MESSAGE_TYPE__DISCONNECT = 1,
  CLIENT_MESSAGE_TYPE__MOVE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_MESSAGE_TYPE)
} ClientMessageType;
typedef enum _ServerMessageType {
  SERVER_MESSAGE_TYPE__OK = 0,
  SERVER_MESSAGE_TYPE__ERROR = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SERVER_MESSAGE_TYPE)
} ServerMessageType;

/* --- messages --- */

struct  Client
{
  ProtobufCMessage base;
  uint64_t key;
  uint64_t instruction;
};
#define CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client__descriptor) \
    , 0, 0 }


struct  UniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planets;
  ProtobufCBinaryData ships;
  ProtobufCBinaryData trash;
  double myplanet;
};
#define UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_data__descriptor) \
    , {0,NULL}, {0,NULL}, {0,NULL}, 0 }


struct  SimplifiedUniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planettrashcount;
  ProtobufCBinaryData trashpership;
  double freetrash;
  double maxtrash;
};
#define SIMPLIFIED_UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&simplified_universe_data__descriptor) \
    , {0,NULL}, {0,NULL}, 0, 0 }


struct  ClientMessage
{
  ProtobufCMessage base;
  ClientMessageType msg_type;
  /*
   *we need this for when the client disconnects
   */
  char *id;
  /*
   *only used when msg_type = MOVE
   */
  uint64_t keys;
};
#define CLIENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_message__descriptor) \
    , CLIENT_MESSAGE_TYPE__CONNECT, NULL, 0 }


/*
 *servidor responde com OK/ERROR e o id da nave de volta
 */
struct  ServerMessage
{
  ProtobufCMessage base;
  ServerMessageType msg_type;
  char *id;
};
#define SERVER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_message__descriptor) \
    , SERVER_MESSAGE_TYPE__OK, NULL }


/* Client methods */
void   client__init
                     (Client         *message);
size_t client__get_packed_size
                     (const Client   *message);
size_t client__pack
                     (const Client   *message,
                      uint8_t             *out);
size_t client__pack_to_buffer
                     (const Client   *message,
                      ProtobufCBuffer     *buffer);
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator);
/* UniverseData methods */
void   universe_data__init
                     (UniverseData         *message);
size_t universe_data__get_packed_size
                     (const UniverseData   *message);
size_t universe_data__pack
                     (const UniverseData   *message,
                      uint8_t             *out);
size_t universe_data__pack_to_buffer
                     (const UniverseData   *message,
                      ProtobufCBuffer     *buffer);
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator);
/* SimplifiedUniverseData methods */
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message);
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData   *message);
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData   *message,
                      uint8_t             *out);
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData   *message,
                      ProtobufCBuffer     *buffer);
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator);
/* ClientMessage methods */
void   client_message__init
                     (ClientMessage         *message);
size_t client_message__get_packed_size
                     (const ClientMessage   *message);
size_t client_message__pack
                     (const ClientMessage   *message,
                      uint8_t             *out);
size_t client_message__pack_to_buffer
                     (const ClientMessage   *message,
                      ProtobufCBuffer     *buffer);
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator);
/* ServerMessage methods */
void   server_message__init
                     (ServerMessage         *message);
size_t server_message__get_packed_size
                     (const ServerMessage   *message);
size_t server_message__pack
                     (const ServerMessage   *message,
                      uint8_t             *out);
size_t server_message__pack_to_buffer
                     (const ServerMessage   *message,
                      ProtobufCBuffer     *buffer);
ServerMessage *
       server_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_message__free_unpacked
                     (ServerMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Client_Closure)
                 (const Client *message,
                  void *closure_data);
typedef void (*UniverseData_Closure)
                 (const UniverseData *message,
                  void *closure_data);
typedef void (*SimplifiedUniverseData_Closure)
                 (const SimplifiedUniverseData *message,
                  void *closure_data);
typedef void (*ClientMessage_Closure)
                 (const ClientMessage *message,
                  void *closure_data);
typedef void (*ServerMessage_Closure)
                 (const ServerMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    client_message_type__descriptor;
extern const ProtobufCEnumDescriptor    server_message_type__descriptor;
extern const ProtobufCMessageDescriptor client__descriptor;
extern const ProtobufCMessageDescriptor universe_data__descriptor;
extern const ProtobufCMessageDescriptor simplified_universe_data__descriptor;
extern const ProtobufCMessageDescriptor client_message__descriptor;
extern const ProtobufCMessageDescriptor server_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msgB_2eproto__INCLUDED */
