/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

#ifndef PROTOBUF_C_msgB_2eproto__INCLUDED
#define PROTOBUF_C_msgB_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Client Client;
typedef struct UniverseData UniverseData;
typedef struct SimplifiedUniverseData SimplifiedUniverseData;


/* --- enums --- */


/* --- messages --- */

struct  Client
{
  ProtobufCMessage base;
  uint64_t key;
  uint64_t instruction;
};
#define CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client__descriptor) \
, 0, 0 }


struct  UniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planets;
  ProtobufCBinaryData ships;
  ProtobufCBinaryData trash;
  double myplanet;
};
#define UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_data__descriptor) \
, {0,NULL}, {0,NULL}, {0,NULL}, 0 }


struct  SimplifiedUniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planettrashcount;
  ProtobufCBinaryData trashpership;
  double freetrash;
  double maxtrash;
};
#define SIMPLIFIED_UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&simplified_universe_data__descriptor) \
, {0,NULL}, {0,NULL}, 0, 0 }


/* Client methods */
void   client__init
                     (Client         *message);
size_t client__get_packed_size
                     (const Client   *message);
size_t client__pack
                     (const Client   *message,
                      uint8_t             *out);
size_t client__pack_to_buffer
                     (const Client   *message,
                      ProtobufCBuffer     *buffer);
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator);
/* UniverseData methods */
void   universe_data__init
                     (UniverseData         *message);
size_t universe_data__get_packed_size
                     (const UniverseData   *message);
size_t universe_data__pack
                     (const UniverseData   *message,
                      uint8_t             *out);
size_t universe_data__pack_to_buffer
                     (const UniverseData   *message,
                      ProtobufCBuffer     *buffer);
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator);
/* SimplifiedUniverseData methods */
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message);
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData   *message);
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData   *message,
                      uint8_t             *out);
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData   *message,
                      ProtobufCBuffer     *buffer);
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Client_Closure)
                 (const Client *message,
                  void *closure_data);
typedef void (*UniverseData_Closure)
                 (const UniverseData *message,
                  void *closure_data);
typedef void (*SimplifiedUniverseData_Closure)
                 (const SimplifiedUniverseData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor client__descriptor;
extern const ProtobufCMessageDescriptor universe_data__descriptor;
extern const ProtobufCMessageDescriptor simplified_universe_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msgB_2eproto__INCLUDED */
