/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msgB.pb-c.h"
void   client__init
                     (Client         *message)
{
  static const Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_data__init
                     (UniverseData         *message)
{
  static const UniverseData init_value = UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t universe_data__get_packed_size
                     (const UniverseData *message)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_data__pack
                     (const UniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_data__pack_to_buffer
                     (const UniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseData *)
     protobuf_c_message_unpack (&universe_data__descriptor,
                                allocator, len, data);
}
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message)
{
  static const SimplifiedUniverseData init_value = SIMPLIFIED_UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData *message)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimplifiedUniverseData *)
     protobuf_c_message_unpack (&simplified_universe_data__descriptor,
                                allocator, len, data);
}
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Client, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instruction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Client, instruction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  1,   /* field[1] = instruction */
  0,   /* field[0] = key */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  2,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_data__field_descriptors[4] =
{
  {
    "Planets",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, planets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ships",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, ships),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Trash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myPlanet",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(UniverseData, myplanet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_data__field_indices_by_name[] = {
  0,   /* field[0] = Planets */
  1,   /* field[1] = Ships */
  2,   /* field[2] = Trash */
  3,   /* field[3] = myPlanet */
};
static const ProtobufCIntRange universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseData",
  "UniverseData",
  "UniverseData",
  "",
  sizeof(UniverseData),
  4,
  universe_data__field_descriptors,
  universe_data__field_indices_by_name,
  1,  universe_data__number_ranges,
  (ProtobufCMessageInit) universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simplified_universe_data__field_descriptors[4] =
{
  {
    "planetTrashCount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, planettrashcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trashPerShip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, trashpership),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freeTrash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, freetrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTrash",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, maxtrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simplified_universe_data__field_indices_by_name[] = {
  2,   /* field[2] = freeTrash */
  3,   /* field[3] = maxTrash */
  0,   /* field[0] = planetTrashCount */
  1,   /* field[1] = trashPerShip */
};
static const ProtobufCIntRange simplified_universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor simplified_universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "",
  sizeof(SimplifiedUniverseData),
  4,
  simplified_universe_data__field_descriptors,
  simplified_universe_data__field_indices_by_name,
  1,  simplified_universe_data__number_ranges,
  (ProtobufCMessageInit) simplified_universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
