/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Common/msgB.proto */

#ifndef PROTOBUF_C_Common_2fmsgB_2eproto__INCLUDED
#define PROTOBUF_C_Common_2fmsgB_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Client Client;
typedef struct Server Server;
typedef struct UniverseData UniverseData;
typedef struct SimplifiedUniverseData SimplifiedUniverseData;


/* --- enums --- */

typedef enum _EnumInput {
  ENUM_INPUT__wKeyDown = 0,
  ENUM_INPUT__aKeyDown = 1,
  ENUM_INPUT__sKeyDown = 2,
  ENUM_INPUT__dKeyDown = 3,
  ENUM_INPUT__wKeyUP = 4,
  ENUM_INPUT__aKeyUP = 5,
  ENUM_INPUT__sKeyUP = 6,
  ENUM_INPUT__dKeyUP = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ENUM_INPUT)
} EnumInput;
typedef enum _EnumType {
  ENUM_TYPE__joinRequest = 0,
  ENUM_TYPE__disconnectRequest = 1,
  ENUM_TYPE__inputConfirmationRequest = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ENUM_TYPE)
} EnumType;

/* --- messages --- */

struct  Client
{
  ProtobufCMessage base;
  uint64_t key;
  EnumInput input;
  EnumType type;
};
#define CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client__descriptor) \
, 0, ENUM_INPUT__wKeyDown, ENUM_TYPE__joinRequest }


struct  Server
{
  ProtobufCMessage base;
  uint64_t key;
  char *broadcastaddr;
  char *movementaddr;
};
#define SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server__descriptor) \
, 0, NULL, NULL }


struct  UniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planets;
  ProtobufCBinaryData ships;
  ProtobufCBinaryData trash;
  uint64_t myplanet;
  protobuf_c_boolean isover;
};
#define UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_data__descriptor) \
, {0,NULL}, {0,NULL}, {0,NULL}, 0, 0 }


struct  SimplifiedUniverseData
{
  ProtobufCMessage base;
  ProtobufCBinaryData planettrashcount;
  ProtobufCBinaryData trashpership;
  double freetrash;
  double maxtrash;
};
#define SIMPLIFIED_UNIVERSE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&simplified_universe_data__descriptor) \
, {0,NULL}, {0,NULL}, 0, 0 }


/* Client methods */
void   client__init
                     (Client         *message);
size_t client__get_packed_size
                     (const Client   *message);
size_t client__pack
                     (const Client   *message,
                      uint8_t             *out);
size_t client__pack_to_buffer
                     (const Client   *message,
                      ProtobufCBuffer     *buffer);
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator);
/* Server methods */
void   server__init
                     (Server         *message);
size_t server__get_packed_size
                     (const Server   *message);
size_t server__pack
                     (const Server   *message,
                      uint8_t             *out);
size_t server__pack_to_buffer
                     (const Server   *message,
                      ProtobufCBuffer     *buffer);
Server *
       server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server__free_unpacked
                     (Server *message,
                      ProtobufCAllocator *allocator);
/* UniverseData methods */
void   universe_data__init
                     (UniverseData         *message);
size_t universe_data__get_packed_size
                     (const UniverseData   *message);
size_t universe_data__pack
                     (const UniverseData   *message,
                      uint8_t             *out);
size_t universe_data__pack_to_buffer
                     (const UniverseData   *message,
                      ProtobufCBuffer     *buffer);
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator);
/* SimplifiedUniverseData methods */
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message);
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData   *message);
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData   *message,
                      uint8_t             *out);
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData   *message,
                      ProtobufCBuffer     *buffer);
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Client_Closure)
                 (const Client *message,
                  void *closure_data);
typedef void (*Server_Closure)
                 (const Server *message,
                  void *closure_data);
typedef void (*UniverseData_Closure)
                 (const UniverseData *message,
                  void *closure_data);
typedef void (*SimplifiedUniverseData_Closure)
                 (const SimplifiedUniverseData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    enum_input__descriptor;
extern const ProtobufCEnumDescriptor    enum_type__descriptor;
extern const ProtobufCMessageDescriptor client__descriptor;
extern const ProtobufCMessageDescriptor server__descriptor;
extern const ProtobufCMessageDescriptor universe_data__descriptor;
extern const ProtobufCMessageDescriptor simplified_universe_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Common_2fmsgB_2eproto__INCLUDED */
