/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Common/msgB.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Common/msgB.pb-c.h"
void   client__init
                     (Client         *message)
{
  static const Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server__init
                     (Server         *message)
{
  static const Server init_value = SERVER__INIT;
  *message = init_value;
}
size_t server__get_packed_size
                     (const Server *message)
{
  assert(message->base.descriptor == &server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server__pack
                     (const Server *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server__pack_to_buffer
                     (const Server *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Server *
       server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Server *)
     protobuf_c_message_unpack (&server__descriptor,
                                allocator, len, data);
}
void   server__free_unpacked
                     (Server *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_data__init
                     (UniverseData         *message)
{
  static const UniverseData init_value = UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t universe_data__get_packed_size
                     (const UniverseData *message)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_data__pack
                     (const UniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_data__pack_to_buffer
                     (const UniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseData *
       universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseData *)
     protobuf_c_message_unpack (&universe_data__descriptor,
                                allocator, len, data);
}
void   universe_data__free_unpacked
                     (UniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simplified_universe_data__init
                     (SimplifiedUniverseData         *message)
{
  static const SimplifiedUniverseData init_value = SIMPLIFIED_UNIVERSE_DATA__INIT;
  *message = init_value;
}
size_t simplified_universe_data__get_packed_size
                     (const SimplifiedUniverseData *message)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simplified_universe_data__pack
                     (const SimplifiedUniverseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simplified_universe_data__pack_to_buffer
                     (const SimplifiedUniverseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimplifiedUniverseData *
       simplified_universe_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimplifiedUniverseData *)
     protobuf_c_message_unpack (&simplified_universe_data__descriptor,
                                allocator, len, data);
}
void   simplified_universe_data__free_unpacked
                     (SimplifiedUniverseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simplified_universe_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Client, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Client, input),
    &enum_input__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Client, type),
    &enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  1,   /* field[1] = input */
  0,   /* field[0] = key */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  3,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Server, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcastAddr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Server, broadcastaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "movementAddr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Server, movementaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server__field_indices_by_name[] = {
  1,   /* field[1] = broadcastAddr */
  0,   /* field[0] = key */
  2,   /* field[2] = movementAddr */
};
static const ProtobufCIntRange server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server",
  "Server",
  "Server",
  "",
  sizeof(Server),
  3,
  server__field_descriptors,
  server__field_indices_by_name,
  1,  server__number_ranges,
  (ProtobufCMessageInit) server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_data__field_descriptors[5] =
{
  {
    "Planets",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, planets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ships",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, ships),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Trash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UniverseData, trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myPlanet",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UniverseData, myplanet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isOver",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UniverseData, isover),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_data__field_indices_by_name[] = {
  0,   /* field[0] = Planets */
  1,   /* field[1] = Ships */
  2,   /* field[2] = Trash */
  4,   /* field[4] = isOver */
  3,   /* field[3] = myPlanet */
};
static const ProtobufCIntRange universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseData",
  "UniverseData",
  "UniverseData",
  "",
  sizeof(UniverseData),
  5,
  universe_data__field_descriptors,
  universe_data__field_indices_by_name,
  1,  universe_data__number_ranges,
  (ProtobufCMessageInit) universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simplified_universe_data__field_descriptors[4] =
{
  {
    "planetTrashCount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, planettrashcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trashPerShip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, trashpership),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freeTrash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, freetrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTrash",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SimplifiedUniverseData, maxtrash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simplified_universe_data__field_indices_by_name[] = {
  2,   /* field[2] = freeTrash */
  3,   /* field[3] = maxTrash */
  0,   /* field[0] = planetTrashCount */
  1,   /* field[1] = trashPerShip */
};
static const ProtobufCIntRange simplified_universe_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor simplified_universe_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "SimplifiedUniverseData",
  "",
  sizeof(SimplifiedUniverseData),
  4,
  simplified_universe_data__field_descriptors,
  simplified_universe_data__field_indices_by_name,
  1,  simplified_universe_data__number_ranges,
  (ProtobufCMessageInit) simplified_universe_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue enum_input__enum_values_by_number[8] =
{
  { "wKeyDown", "ENUM_INPUT__wKeyDown", 0 },
  { "aKeyDown", "ENUM_INPUT__aKeyDown", 1 },
  { "sKeyDown", "ENUM_INPUT__sKeyDown", 2 },
  { "dKeyDown", "ENUM_INPUT__dKeyDown", 3 },
  { "wKeyUP", "ENUM_INPUT__wKeyUP", 4 },
  { "aKeyUP", "ENUM_INPUT__aKeyUP", 5 },
  { "sKeyUP", "ENUM_INPUT__sKeyUP", 6 },
  { "dKeyUP", "ENUM_INPUT__dKeyUP", 7 },
};
static const ProtobufCIntRange enum_input__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex enum_input__enum_values_by_name[8] =
{
  { "aKeyDown", 1 },
  { "aKeyUP", 5 },
  { "dKeyDown", 3 },
  { "dKeyUP", 7 },
  { "sKeyDown", 2 },
  { "sKeyUP", 6 },
  { "wKeyDown", 0 },
  { "wKeyUP", 4 },
};
const ProtobufCEnumDescriptor enum_input__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "enumInput",
  "enumInput",
  "EnumInput",
  "",
  8,
  enum_input__enum_values_by_number,
  8,
  enum_input__enum_values_by_name,
  1,
  enum_input__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue enum_type__enum_values_by_number[3] =
{
  { "joinRequest", "ENUM_TYPE__joinRequest", 0 },
  { "disconnectRequest", "ENUM_TYPE__disconnectRequest", 1 },
  { "inputConfirmationRequest", "ENUM_TYPE__inputConfirmationRequest", 2 },
};
static const ProtobufCIntRange enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex enum_type__enum_values_by_name[3] =
{
  { "disconnectRequest", 1 },
  { "inputConfirmationRequest", 2 },
  { "joinRequest", 0 },
};
const ProtobufCEnumDescriptor enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "enumType",
  "enumType",
  "EnumType",
  "",
  3,
  enum_type__enum_values_by_number,
  3,
  enum_type__enum_values_by_name,
  1,
  enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
